
[entryPoints]
    [entryPoints.http]
    address = ":8080"

    [entryPoints.private]
    address = ":8081"

[api]
  entryPoint = "private"
  dashboard = false

[file]
  filename = "routes.toml"
  watch = true
